// Committed shim so `tsc --noEmit` (the `typecheck` script / CI) resolves the
// same ambient types Next declares — most importantly static image imports
// (src/app/page.tsx imports .png screenshots). Next normally provides these via
// next-env.d.ts, but that file is generated by `next build` and gitignored, so a
// clean CI checkout that runs typecheck BEFORE build wouldn't have it → TS2307.
// Same `<reference>` sources as next-env.d.ts, so this is idempotent when it's
// also present locally.
/// <reference types="next" />
/// <reference types="next/image-types/global" />
